version: "3"

services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - 8000:8000
    env_file:
      - .env
    entrypoint: ./docker/python/entrypoint.sh
    depends_on:
      - postgres
      - mongo
  postgres:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  mongo:
    build:
      context: .
      dockerfile: docker/mongodb/Dockerfile
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./static:/static
    depends_on:
      - python
volumes:
  pgdata:
  mongodata:
  static: